CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    date_joined DATETIME DEFAULT CURRENT_TIMESTAMP,
    role INT(3),
    last_login DATETIME,
    profile_pic VARCHAR(255)
)